services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: medusa_postgres_frostlord
    restart: unless-stopped
    environment:
      POSTGRES_DB: frostlord
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 100801
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - medusa_network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: medusa_redis_frostlord
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - medusa_network

  # Medusa Server
  # This service runs the Medusa backend application
  medusa:
    build: 
      context: ./backend
      dockerfile: ../Dockerfile
    container_name: medusa_backend_frostlord
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:100801@postgres:5432/frostlord?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-super-secret-jwt-key-for-development
      - COOKIE_SECRET=your-super-secret-cookie-key-for-development
      - MEDUSA_BACKEND_URL=http://localhost:9000
      - STORE_CORS=http://localhost:8000,http://localhost:3000
      - ADMIN_CORS=http://localhost:7001,http://localhost:7000,http://localhost:9000
      - AUTH_CORS=http://localhost:8000,http://localhost:3000
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - medusa_network
    working_dir: /app

volumes:
  postgres_data:

networks:
  medusa_network:
    driver: bridge