[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && npm run build && npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
numReplicas = 1

[build.context]
path = "backend"

[build.environment]
NIXPACKS_PKG_MANAGER = "npm"
